name = "Playbook"
grammar = "yaml"
path_suffixes = ["playbook.yaml", "playbook.yml"]
line_comments = ["#"]
block_comments = []
autoclose_before = "]'\""
brackets = [
    { start = "[", end = "]", close = true, newline = false },
    { start = "{", end = "}", close = true, newline = true },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["string"] },
]
word_characters = ["_", "-", "."]
