[package]
name = "bpmn-lite-server"
version = "0.1.0"
edition = "2021"

[features]
default = []
postgres = ["bpmn-lite-core/postgres", "dep:sqlx"]

[dependencies]
bpmn-lite-core = { path = "../bpmn-lite-core" }
tonic = { workspace = true }
prost = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uuid = { workspace = true }
serde_json = { workspace = true }
tokio-stream = "0.1"
sqlx = { workspace = true, optional = true }

[dev-dependencies]
tokio = { workspace = true, features = ["test-util"] }

[build-dependencies]
tonic-build = "0.12"
