[package]
name = "governed_query_proc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "parsing", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
serde = { version = "1.0", features = ["derive"] }
bincode = "1"

[dev-dependencies]
trybuild = "1"
